packages:
    - "apps/*"
    - "packages/*"
    - "tooling/*"

catalog:
    "@tanstack/react-query": ^5.59.15
    "@trpc/client": ^11.0.0.-rc.477
    "@trpc/react-query": ^11.0.0.-rc.477
    "@trpc/server": ^11.0.0.-rc.477
    eslint: ^9.12.0
    prettier: ^3.3.0
    tailwindcss: ^3.4.14
    zod: ^3.23.8
    "@types/node": ^20
    autoprefixer: ^10.4.19
    postcss: ^8
    typescript: ^5
    "next-auth": 5.0.0-beta.19
    "react-icons": ^5.2.1
    eslint-config-next: ^15.0.3
    "@auth/prisma-adapter": ^2.2.0
    "@hookform/resolvers": ^3.6.0
    "lucide-react": ^0.394.0
    "date-fns": ^3.6.0
    "react-hook-form": ^7.51.5
    "recharts": ^2.12.7
    "react-day-picker": ^8.10.1
    "@eslint/eslintrc": ^3.0.0

catalogs:
    react18:
        react: 18.3.1
        react-dom: 18.3.1
        "@types/react": 18.3.11
        "@types/react-dom": 18.3.1

    react19:
        react: 19.0.0-rc-66855b96-20241106
        react-dom: 19.0.0-rc-66855b96-20241106
        "@types/react": ^18
        "@types/react-dom": ^18

    next15:
        next: 15.0.3

    prisma:
        prisma: 5.22.0
        "@prisma/client": 5.22.0
        "@prisma/nextjs-monorepo-workaround-plugin": 5.22.0
